### ISSUE TITLE
More guidance on how to use Secrets?

### ISSUE THREAD

**Issue by joshmillgate** [lxieyang/chrome-extension-boilerplate-react#20]
I have created a file at root called secrets.development.js:

```
export default config = {
  apiKey: 'string',
  authDomain: 'string',
  databaseURL: 'string'
};

```

1.  How do I import this object within my files?
2. How do I call to the specific key value pairs in my document?

Thanks!

**Comment by lxieyang** [comment]
yeah, if you do `import Configs from './secres.development';`, and then do `Configs.apiKey` of `Configs.authDomain` to access the specific configs.
Hopefully, you've already put some restrictions on how your API keys can be used, otherwise having these keys present in the code might still not be a good idea. Try hiding them in an `.env` file might be a better idea. See here: https://dev.to/benjaminmock/how-to-handle-secrets-in-node-js-environment-variables-2251
