### ISSUE TITLE
SharedArrayBuffer will require cross-origin isolation as of M91, around

### ISSUE THREAD

**Issue by RathanakSreang** [lxieyang/chrome-extension-boilerplate-react#33]
I have got this warnning message
```
typeof SharedArrayBuffer === 'function' ? new SharedArrayBuffer(profilingStateSize * Int32Array.BYTES_PER_ELEMENT) : // $FlowFixMe Flow doesn't know about ArrayBuffer
```

How can I fix it?

**Comment by lwouis** [comment]
You probably want to update React. See [this commit fixing the same issue](https://github.com/hcl1687/iframe-channel/commit/6651191874f81e5256fbeedc14ae2cfa27f33902).

**Comment by RathanakSreang** [comment]
@lwouis  I try upgrade my react, but still got error.  WHen I click on popup.

**Comment by lwouis** [comment]
Yeah i noticed i have it too. I checked the dependency called `scheduler` (from the react dependency), and it still contains the symbol, even in 17.0.2 where they say they removed its usage.

So i'm thinking that it's unused code and that it's going to work without the symbol being resolved by Chrome when Chrome bans it. However i'm not 100% sure. I think the warning exists because the code contains the symbol vs its actually used. In any case, report this on the React repo, not here

**Comment by willliuwillliu** [comment]
I'm having this issue too. Tried upgrading react to .02 from .01 and did not work
