### ISSUE TITLE
How do disable newTab redirect

### ISSUE THREAD

**Issue by swaitw** [lxieyang/chrome-extension-boilerplate-react#36]
sorry for disturb, i am very new for chrome-extention, i did not find any info about how to disable or enbale dirrent pages.

waiting for your help and thanks.

**Comment by littlemyx** [comment]
If I understood you correct the solution is just to remove 
```
"chrome_url_overrides": {
    "newtab": "newtab.html"
  },
```
from the manifest.json

**Comment by VladSez** [comment]
I have the same issue and the @littlemyx solution did not help :(

**Comment by VladSez** [comment]
I have removed these strings from webpack.config.js
```js   
newtab: path.join(__dirname, 'src', 'pages', 'Newtab', 'index.jsx'),
```

```js
new HtmlWebpackPlugin({
      template: path.join(__dirname, 'src', 'pages', 'Newtab', 'index.html'),
      filename: 'newtab.html',
      chunks: ['newtab'],
      cache: false,
    }),
```
also this from manifest.json

```js
"chrome_url_overrides": {
    "newtab": "newtab.html"
  },
```
and now i don't have a newTab redirect :)

**Comment by surajsharma** [comment]
> ```js
> newtab
> ```

did all this but the new tab redirect still persists

**Comment by VladSez** [comment]
Did you restart the server?

**Comment by orkunkilic** [comment]
I have same problem, even though I deleted from manifest and webpack config, chrome still redirects me to newtab page. @VladSez

**Comment by rasulkireev** [comment]
I was having the same issue, until I "restarted" the plugin:
![image](https://github.com/lxieyang/chrome-extension-boilerplate-react/assets/8257474/a774552d-73db-4a44-9c2d-e68e82ef2bbe)

**Comment by andrewglanzzz** [comment]
Seems like this issue is still persisting. I followed the instructions from @VladSez and while everything builds and functions, opening a newtab will still redirect me while throwing the error "ERR_FILE_NOT_FOUND". 

It seems like the steps above should completely remove any newtab elements from the extension. Any idea why this is happening?

![Capture](https://github.com/lxieyang/chrome-extension-boilerplate-react/assets/60935069/86d76e93-4eb8-422b-ba63-50d33da408e6)
