### ISSUE TITLE
npm ERR! gyp ERR! not ok

### ISSUE THREAD

**Issue by khalidMhd** [lxieyang/chrome-extension-boilerplate-react#50]

**Comment by Goku-kun** [comment]
```
npm ERR! gyp ERR! node -v v15.12.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

If you're referring to this error, then I saw this error because I had aliased python2 with python3 for the command `python`.

You can install python2 if you're not having it installed or just make sure that the command `python` is available in the directory that you've cloned this repository in.

That'll solve your issue.
